name: Build nomad-wait for Linux x86_64

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build from nomad-wait.go
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files
      run: ls -la

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'
        cache: true
        
    - name: Setup Go MOD
      run: ｜
        go mod tidy   

    - name: Build from single file
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
          -o nomad-wait \
          -ldflags="-s -w" \
          nomad-wait.go

    - name: Verify binary
      run: |
        echo "=== 文件信息 ==="
        file nomad-wait
        echo "=== 依赖检查 ==="
        ldd nomad-wait 2>/dev/null || echo "✅ 静态二进制文件"
        echo "=== 文件大小 ==="
        ls -lh nomad-wait
        echo "=== 测试执行 ==="
        ./nomad-wait --version || ./nomad-wait --help || echo "✅ 二进制文件可执行"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nomad-wait-linux-amd64
        path: nomad-wait
        retention-days: 30
